name: 🐞报告Bug
description: 报告bug，请先查看常见问题及搜索issue列表中有无你要提的问题
title: "[Bug]: "
body:
- type: checkboxes
  id: check-answer
  attributes:
    label: 解决方案检查
    description: 请确保你已完成以下所有操作
    options:
      - label: 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，并没有发现类似的问题
        required: true
- type: input
  id: version
  attributes:
    label: 青龙版本
    description: 你使用什么版本的青龙？
    placeholder: "例如 2.10.13"
  validations:
    required: true
- type: input
  id: operating-system-version
  attributes:
    label: 操作系统
    description: 您使用的是什么操作系统？
    placeholder: "例如 Ubuntu 20.04"
  validations:
    required: true
- type: textarea
  id: vulnerability-feedback
  attributes:
    label: 问题反馈
    description: 对漏洞的内容简明描述
  validations:
    required: true
- type: textarea
  id: additional-information
  attributes:
    label: 附加信息
    description: 如果你的问题需要进一步解释，或者想要表达其他内容，请在此处添加更多信息。（直接把图片、视频拖到编辑框即可添加图片或视频）

